module.exports = {

    STATUS: {
        REQUEST_RECEIVED: 'REQUEST_RECEIVED',

        EXPORT_TRIGGERED: 'EXPORT_TRIGGERED',
        EXPORT_IN_PROGRESS: 'EXPORT_IN_PROGRESS',
        EXPORT_COMPLETED: 'EXPORT_COMPLETED',

        FILE_DOWNLOADED: 'FILE_DOWNLOADED',
        EXCEL_UPDATED: 'EXCEL_UPDATED',

        IMPORT_TRIGGERED: 'IMPORT_TRIGGERED',
        IMPORT_IN_PROGRESS: 'IMPORT_IN_PROGRESS',
        IMPORT_COMPLETED: 'IMPORT_COMPLETED',

        SUBMIT_TRIGGERED: 'SUBMIT_TRIGGERED',
        SUBMIT_IN_PROGRESS: 'SUBMIT_IN_PROGRESS',
        SUBMIT_COMPLETED: 'SUBMIT_COMPLETED',
        JOB_STATUS_UPDATE: 'JOB_STATUS_UPDATE',
        POLLING_ERROR: 'POLLING_ERROR',
        IMPORT_FAILED: 'IMPORT_FAILED',
        EXPORT_FAILED: 'EXPORT_FAILED',
        SUBMIT_FAILED: 'SUBMIT_FAILED',
        FILE_DOWNLOAD_FAILED: 'FILE_DOWNLOAD_FAILED',

        FAILED: 'FAILED'
    },
    TIME: {
        POLL_TIMEOUT: 300000, // 5 minutes  
        POLL_INTERVAL: 10000 // 10 seconds
    }
}